# Generated by Django 5.2.4 on 2025-07-15 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='שם החברה')),
                ('contact_person', models.CharField(max_length=100, verbose_name='איש קשר')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('product_type', models.CharField(max_length=100, verbose_name='סוג מוצר')),
                ('quantity', models.IntegerField(verbose_name='כמות')),
                ('description', models.TextField(verbose_name='תיאור הצורך')),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='business_quotes/logos/', verbose_name='קובץ לוגו')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('in_progress', 'בעבודה'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'בקשת הצעת מחיר עסקית',
                'verbose_name_plural': 'בקשות הצעות מחיר עסקיות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם הקטגוריה')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'קטגוריה',
                'verbose_name_plural': 'קטגוריות',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם העיצוב')),
                ('design_data', models.JSONField(verbose_name='נתוני עיצוב')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='designs/previews/')),
                ('is_public', models.BooleanField(default=False, verbose_name='עיצוב ציבורי')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'עיצוב אישי',
                'verbose_name_plural': 'עיצובים אישיים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם המוצר')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='תיאור')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר')),
                ('fabric_type', models.CharField(choices=[('cotton', 'כותנה'), ('polyester', 'פוליאסטר'), ('blend', 'תערובת'), ('bamboo', 'במבוק'), ('linen', 'פשתן')], max_length=20, verbose_name='סוג בד')),
                ('colors_available', models.JSONField(default=list, verbose_name='צבעים זמינים')),
                ('sizes_available', models.JSONField(default=list, verbose_name='מידות זמינות')),
                ('image', models.ImageField(upload_to='products/', verbose_name='תמונה ראשית')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('is_featured', models.BooleanField(default=False, verbose_name='מוצר מומלץ')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='כמות במלאי')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
            options={
                'verbose_name': 'תמונת מוצר',
                'verbose_name_plural': 'תמונות מוצר',
            },
        ),
    ]
