# Generated by Django 5.2.4 on 2025-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customdesign_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_print',
            field=models.BooleanField(default=True, verbose_name='ניתן להדפסה'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_print_height',
            field=models.FloatField(blank=True, null=True, verbose_name='גובה הדפסה מקסימלי (ס"מ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_print_width',
            field=models.FloatField(blank=True, null=True, verbose_name='רוחב הדפסה מקסימלי (ס"מ)'),
        ),
    ]
