# Generated by Django 5.2.4 on 2025-07-19 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_can_print_product_max_print_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='מזהה סשן')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='כותרת השיחה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='main.product', verbose_name='מוצר')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'שיחת AI',
                'verbose_name_plural': 'שיחות AI',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'משתמש'), ('ai', 'AI'), ('system', 'מערכת')], max_length=10, verbose_name='סוג הודעה')),
                ('content', models.TextField(verbose_name='תוכן ההודעה')),
                ('translated_prompt', models.TextField(blank=True, verbose_name='פרומפט מתורגם')),
                ('generated_image_url', models.URLField(blank=True, verbose_name='קישור לתמונה')),
                ('ai_service_used', models.CharField(blank=True, max_length=50, verbose_name='שירות AI בשימוש')),
                ('metadata', models.JSONField(default=dict, verbose_name='מטא-דאטה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.aiconversation')),
            ],
            options={
                'verbose_name': 'הודעת AI',
                'verbose_name_plural': 'הודעות AI',
                'ordering': ['created_at'],
            },
        ),
    ]
